"""Integrated social/music flows, real audio sync and simulated mobile keyboard viewport."""
import json,sqlite3,sys,tempfile,threading,wave
from pathlib import Path
from werkzeug.security import generate_password_hash
from werkzeug.serving import make_server
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from app import create_app
from jump_browser_check import QuietHandler
H={'X-Requested-With':'Flix'};OUT=ROOT/'test-results'
with tempfile.TemporaryDirectory() as folder:
 app=create_app(folder,testing=True)
 with sqlite3.connect(Path(folder)/'vyra.sqlite3') as db:db.execute("UPDATE users SET password=?,name='Theo Almeida' WHERE role='admin'",(generate_password_hash('Admin-browser-123'),))
 sound=Path(folder)/'trilha.wav'
 with wave.open(str(sound),'wb') as w:w.setparams((1,2,8000,0,'NONE','not compressed'));w.writeframes(b'\0\0'*8000*90)
 server=make_server('127.0.0.1',8144,app,threaded=True,request_handler=QuietHandler);threading.Thread(target=server.serve_forever,daemon=True).start();url='http://localhost:8144'
 try:
  with sync_playwright() as pw:
   browser=pw.chromium.launch(executable_path='/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',headless=True,args=['--no-sandbox','--autoplay-policy=no-user-gesture-required'])
   hc=browser.new_context(viewport={'width':1440,'height':1000});gc=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True)
   assert hc.request.post(url+'/api/auth/login',headers=H,data={'email':'admin@vyra.local','password':'Admin-browser-123'}).ok
   admin=hc.request.get(url+'/api/bootstrap').json()['user'];aid=admin['id']
   r=hc.request.post(url+'/api/admin/users',headers=H,data={'name':'Luna Martins','username':'luna','email':'luna@example.com','password':'Community-123'});assert r.ok,r.text();uid=r.json()['user']['id']
   assert gc.request.post(url+'/api/auth/login',headers=H,data={'email':'luna@example.com','password':'Community-123'}).ok
   hc.request.post(url+'/api/social/friends',headers=H,data={'username':'luna'});gc.request.patch(url+'/api/social/friends/'+aid,headers=H,data={})
   host=hc.new_page();guest=gc.new_page();errors=[]
   for p in (host,guest):p.on('pageerror',lambda e:errors.append(str(e)))
   try:
    guest.goto(url+'/conta');guest.locator('[data-fs=verification]').click();guest.locator('[name=reason]').fill('Criadora de conteúdo na nossa comunidade de cinema.');guest.locator('#fs-verification [type=submit]').click();expect(guest.locator('#fs-verification')).not_to_be_visible()
    host.goto(url+'/admin?tab=verifications');host.locator('[data-fs=verify-approve]').click();expect(host.locator('[data-fs=verify-remove]')).to_be_visible();guest.goto(url+'/comunidade/perfil/luna');expect(guest.locator('.cm-profile-title .fs-verified')).to_be_visible()
    host.goto(url+'/comunidade?tab=pages');host.locator('[data-fs=space-new]').click();host.locator('#fs-space [name=name]').fill('Clube das boas histórias');host.locator('#fs-space [name=username]').fill('boashistorias');host.locator('#fs-space button.btn-primary').click();host.wait_for_url('**/espaco/boashistorias');host.locator('.fs-space-compose').click();host.locator('[name=title]').fill('Sessão da semana');host.locator('#cx-post-body').fill('Uma nova descoberta :heart:');host.get_by_role('button',name='Publicar publicação',exact=True).click();host.wait_for_url('**/post/*');expect(host.locator('.cx-post-header')).to_contain_text('Clube das boas histórias')
    host.goto(url+'/comunidade?tab=friends');host.locator('[data-fs=group-new]').click();host.locator('#fs-group [name=name]').fill('Clube do cinema');host.locator('#fs-group [name=members]').check();host.get_by_role('button',name='Criar grupo',exact=True).click();host.wait_for_url('**group=*');gid=host.url.split('group=')[1];expect(host.locator('#fh-message')).to_be_visible();host.locator('#fh-body').fill('Vamos assistir? :heart:');host.locator('#fh-message [type=submit]').click();expect(host.locator('#fh-messages')).to_contain_text('Vamos assistir? ❤️')
    guest.goto(url+'/comunidade?tab=friends&group='+gid);expect(guest.locator('#fh-messages')).to_contain_text('Vamos assistir? ❤️');guest.locator('#fh-body').focus()
    guest.evaluate("Object.defineProperty(visualViewport,'height',{configurable:true,get:()=>430});Object.defineProperty(visualViewport,'offsetTop',{configurable:true,get:()=>45});visualViewport.dispatchEvent(new Event('resize'))")
    guest.wait_for_timeout(150);metrics=guest.locator('#fh-message').evaluate('(e)=>{const r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:r.height}}');assert metrics['height']>30 and metrics['top']>=45 and metrics['bottom']<=476,metrics
    guest.locator('#fh-body').fill('Agora o teclado não cobre a mensagem 🔥');guest.locator('#fh-message [type=submit]').click();expect(host.locator('#fh-messages')).to_contain_text('Agora o teclado',timeout=15000);guest.screenshot(path=str(OUT/'evolution-mobile-keyboard.png'));guest.evaluate("delete visualViewport.height;delete visualViewport.offsetTop;visualViewport.dispatchEvent(new Event('resize'))")
    host.goto(url+'/comunidade/criar/story');host.locator('.cx-media-start [data-cx-upload=clips]').set_input_files(str(ROOT/'static/assets/hero.png'));expect(host.locator('#cx-editor-preview img')).to_be_visible();host.locator('[data-cx=sticker-panel]').click();host.locator('[data-cx=sticker-pick]').first.click();host.locator('[data-cx=mention-panel]').click();host.locator('#cx-mention-query').fill('luna');host.locator('[data-cx=mention-search]').click();host.locator('[data-cx=mention-pick]').click();host.locator('.cx-tool-grid [data-cx=draw-toggle]').click();expect(host.locator('#cx-editor-preview .cx-scene')).to_have_class(__import__('re').compile('is-drawing'));host.locator('#cx-editor-preview .cx-scene').scroll_into_view_if_needed();box=host.locator('#cx-editor-preview .cx-scene').bounding_box();host.mouse.move(box['x']+25,box['y']+60);host.mouse.down();host.mouse.move(box['x']+150,box['y']+100,steps=15);host.mouse.up();expect(host.locator('#cx-editor-preview polyline')).to_have_count(1);host.locator('#cx-draw-panel [data-cx=draw-toggle]').click();host.locator('.cx-steps [data-step="3"]').click();host.get_by_label('Legenda').fill('Nossa noite de cinema');host.get_by_role('button',name='Publicar story',exact=True).first.click();host.wait_for_url('**/comunidade');story=hc.request.get(url+'/api/community/stories').json()['stories'][0];assert story['thumbnail'];assert gc.request.get(url+story['thumbnail']).ok
    guest.goto(url+'/comunidade?story='+story['id']);expect(guest.locator('#cx-play-composition img')).to_be_visible();expect(guest.locator('#cx-play-composition polyline')).to_have_count(1);assert guest.locator('#cx-play-composition img').evaluate('(i)=>i.naturalWidth>0');guest.locator('#modal [data-action=close]').click()
    host.goto(url+'/comunidade?tab=music');host.locator('[data-music=import]').click();host.locator('#fm-import-file').set_input_files(str(sound));host.locator('#fm-import [name=title]').fill('Trilha da nossa turma');host.locator('#fm-import [type=submit]').click();host.wait_for_url('**track=*');tid=host.url.split('track=')[1];host.locator('[data-fm-card="'+tid+'"] [data-music=track-play]').first.click();host.wait_for_function("()=>document.querySelector('#fm-engine audio')?.currentTime>1");host.evaluate('window.testAudio=document.querySelector("#fm-engine audio")');host.evaluate("navigate('/comunidade')");host.wait_for_url('**/comunidade');assert host.evaluate('testAudio===document.querySelector("#fm-engine audio")&&!testAudio.paused');host.screenshot(path=str(OUT/'evolution-persistent-music.png'))
    host.evaluate("navigate('/comunidade?tab=music')");host.wait_for_url('**tab=music');host.locator('[data-music=playlist-new]').click();host.locator('#fm-playlist-new [name=name]').fill('Cinema em notas');host.locator('#fm-playlist-new [type=submit]').click();host.wait_for_url('**playlist=*');pid=host.url.split('playlist=')[1];assert hc.request.put(url+'/api/music/playlists/'+pid,headers=H,data={'tracks':[tid]}).ok
    host.goto(url+'/comunidade/perfil/'+admin['username']);expect(host.locator('.fm-profile-playlists')).to_contain_text('Cinema em notas')
    host.goto(url+'/comunidade?tab=music&track='+tid);host.locator('[data-music=room-new]').first.click();host.locator('#fm-room-new [name=title]').fill('Ouvindo com a turma');host.locator('#fm-room-new [type=submit]').click();host.wait_for_url('**/comunidade/sala/*');rid=host.url.rsplit('/',1)[1];expect(host.locator('#fm-room-layout')).to_be_visible();guest.goto(url+'/comunidade/sala/'+rid);expect(guest.locator('#cm-admission-status')).to_contain_text('Aguardando');expect(host.locator('[data-music=room-accept]')).to_be_visible(timeout=15000);host.locator('[data-music=room-accept]').click();expect(guest.locator('.rm-tabs')).to_be_visible(timeout=15000);expect(guest.locator('.rm-tabs [data-tab=chat]')).to_have_attribute('aria-current','page')
    host.locator('#fm-room-now [data-music=toggle]').click();host.wait_for_function("()=>document.querySelector('#fm-engine audio')?.currentTime>1");guest.locator('[data-cm=room-enable]').click();guest.wait_for_function("()=>document.querySelector('#cm-room-media')?.currentTime>1");host.locator('#fm-seek').fill('24');host.locator('#fm-seek').dispatch_event('change');guest.wait_for_function("()=>document.querySelector('#cm-room-media')?.currentTime>=24");h=host.locator('#fm-engine audio').evaluate('(a)=>a.currentTime');g=guest.locator('#cm-room-media').evaluate('(a)=>a.currentTime');assert abs(h-g)<2,(h,g)
    guest.wait_for_function("()=>document.querySelector('#cm-room-media').currentTime>34");assert gc.request.get(url+'/api/community/profiles/luna').json()['profile']['recent_music']['id']==tid
    host.locator('#fm-room-now [data-music=toggle]').click();guest.wait_for_function("()=>document.querySelector('#cm-room-media')?.paused");guest.locator('#cm-room-message input[name=body]').fill('Estamos na mesma música 🎵');guest.locator('#cm-room-message [type=submit]').click();expect(host.locator('#fm-room-log')).to_contain_text('Estamos na mesma música');expect(guest.locator('.rm-tabs [data-tab=chat]')).to_have_attribute('aria-current','page');assert guest.evaluate('document.documentElement.scrollWidth<=innerWidth');host.screenshot(path=str(OUT/'evolution-music-room-desktop.png'));guest.screenshot(path=str(OUT/'evolution-music-room-mobile.png'),full_page=True)
    host.goto(url+'/admin?tab=music');expect(host.locator('.fm-admin-track')).to_contain_text('Trilha da nossa turma');host.locator('[data-music=admin-feature]').click();expect(host.locator('[data-music=admin-feature]')).to_have_text('Remover destaque');host.locator('[data-music=admin-edit]').click();host.locator('#fm-admin-edit [name=genre]').fill('Trilha sonora');host.locator('#fm-admin-edit [type=submit]').click();expect(host.locator('.fm-admin-track')).to_contain_text('Trilha sonora')
    host.goto(url+'/admin?tab=spaces');expect(host.locator('.fs-review-list')).to_contain_text('Clube das boas histórias');host.locator('[data-fs=admin-space-status]').click();expect(host.locator('[data-fs=admin-space-status]')).to_have_text('Reativar espaço');host.locator('[data-fs=admin-space-status]').click();expect(host.locator('[data-fs=admin-space-status]')).to_have_text('Ocultar espaço')
    r=hc.request.post(url+'/api/community/posts',headers=H,data={'kind':'music','title':'A trilha de hoje','body':'Cinema em notas','url':hc.request.get(url+'/api/music/tracks/'+tid).json()['track']['url'],'music_id':tid});assert r.ok,r.text();host.goto(url+'/comunidade/post/'+r.json()['id']);expect(host.locator('[data-fm-card]')).to_have_count(1);expect(host.locator('[data-fm-label]')).to_contain_text('Tocando agora')
    assert not errors,errors
    print(json.dumps({'verification':True,'pages':True,'group_chat':True,'mobile_keyboard_viewport':metrics,'photo_story_thumbnail_draw_mention_sticker':True,'persistent_actual_audio':True,'profile_playlist':True,'room_admission':True,'room_audio_sync_drift':abs(h-g),'room_text_chat':True,'page_errors':errors}))
   except Exception:
    for name,p in [('host',host),('guest',guest)]:
     try:p.screenshot(path=str(OUT/f'evolution-failure-{name}.png'),full_page=True)
     except Exception:pass
    raise
   finally:browser.close()
 finally:server.shutdown()
