"""Dedicated creators, social controls, crops, badges and phone layout in an isolated app."""
import json,sqlite3,sys,tempfile,threading,time
from pathlib import Path
from werkzeug.security import generate_password_hash
from werkzeug.serving import make_server
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from app import create_app
from jump_browser_check import QuietHandler
H={'X-Requested-With':'Flix'};OUT=ROOT/'test-results';OUT.mkdir(exist_ok=True)
with tempfile.TemporaryDirectory() as folder:
    app=create_app(folder,testing=True);dbpath=Path(folder)/'vyra.sqlite3'
    with sqlite3.connect(dbpath) as db:
        episode=db.execute("SELECT id FROM episodes WHERE content_id='neon' ORDER BY season,number LIMIT 1").fetchone()[0]
        db.execute("UPDATE users SET password=?,name='Theo Almeida' WHERE role='admin'",(generate_password_hash('Admin-browser-123'),))
    server=make_server('127.0.0.1',8139,app,threaded=True,request_handler=QuietHandler);threading.Thread(target=server.serve_forever,daemon=True).start();url='http://localhost:8139'
    try:
      with sync_playwright() as pw:
        browser=pw.chromium.launch(executable_path='/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',headless=True,args=['--no-sandbox'])
        hc=browser.new_context(viewport={'width':1440,'height':1000});gc=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True)
        assert hc.request.post(url+'/api/auth/login',headers=H,data={'email':'admin@vyra.local','password':'Admin-browser-123'}).ok
        aid=hc.request.get(url+'/api/bootstrap').json()['user']['id'];au=hc.request.get(url+'/api/bootstrap').json()['user']['username']
        r=hc.request.post(url+'/api/admin/users',headers=H,data={'name':'Luna Martins','username':'luna','email':'luna@example.com','password':'Community-123'});assert r.ok,r.text();gid=r.json()['user']['id']
        assert gc.request.post(url+'/api/auth/login',headers=H,data={'email':'luna@example.com','password':'Community-123'}).ok
        hc.request.post(url+'/api/social/friends',headers=H,data={'username':'luna'});gc.request.patch(url+'/api/social/friends/'+aid,headers=H,data={})
        host=hc.new_page();guest=gc.new_page();errors=[]
        for p in (host,guest):p.on('pageerror',lambda e:(errors.append(str(e)),print('PAGEERROR',str(e),flush=True)))
        try:
          host.goto(url+'/comunidade/criar');expect(host.locator('.cx-format-grid>a')).to_have_count(5)
          host.get_by_role('link',name='Um filme',exact=False).click();host.get_by_label('Título',exact=True).fill('Horizontes de outubro');host.get_by_label('Gênero',exact=True).fill('Drama');host.get_by_label('Sinopse',exact=True).fill('Uma viagem que muda tudo.');host.get_by_label('Link do filme em MP4').fill('https://example.com/movie.mp4')
          host.locator('[data-cx-upload=cover]').set_input_files(str(ROOT/'static/assets/hero.png'));expect(host.get_by_role('dialog',name='Ajustar foto')).to_be_visible();host.get_by_label('Zoom da foto').fill('1.5');box=host.locator('.cx-crop-box canvas').bounding_box();host.mouse.move(box['x']+80,box['y']+80);host.mouse.down();host.mouse.move(box['x']+120,box['y']+110,steps=5);host.mouse.up();host.get_by_role('button',name='Usar este recorte').click();expect(host.locator('#cx-cover-preview img')).to_be_visible(timeout=15000);host.screenshot(path=str(OUT/'experience-movie-desktop.png'));host.get_by_role('button',name='Publicar filme',exact=True).click();host.wait_for_url('**/comunidade/post/*');pid=host.url.rsplit('/',1)[-1];expect(host.locator('.cx-feed-copy')).to_contain_text('Drama',ignore_case=True)
          guest.goto(url+'/comunidade/post/'+pid);guest.get_by_label('Seu comentário').fill('Quero assistir com @'+au);expect(guest.locator('.cx-mention-results')).to_be_visible();guest.locator('.cx-mention-results button').first.click();guest.get_by_role('button',name='Comentar',exact=True).click();expect(guest.locator('.cx-comments .cx-comment')).to_have_count(1);guest.locator('.cx-comments .cx-overflow>summary').click();guest.get_by_role('button',name='Editar comentário',exact=True).click();expect(guest.locator('#cx-comment-edit')).to_be_visible();guest.locator('#cx-comment-edit textarea').fill('Um filme para a próxima sessão 🍿');guest.locator('#cx-comment-edit [type=submit]').click();expect(guest.locator('.cx-comments')).to_contain_text('editado')
          host.reload();expect(host.locator('.cx-latest-comment')).to_contain_text('próxima sessão');host.locator('.cx-comments .cx-overflow>summary').click();host.get_by_role('button',name='Ocultar comentário',exact=True).click();expect(host.locator('.cx-comments .is-hidden')).to_have_count(1)
          host.locator('.cx-post-header summary').click();host.get_by_role('button',name='Ocultar curtidas',exact=True).click();host.locator('.cx-post-header summary').click();host.get_by_role('button',name='Privar publicação',exact=True).click();host.wait_for_url('**status=private');assert gc.request.get(url+'/api/community/posts/'+pid).status==404
          host.locator('.cx-post-header summary').click();host.get_by_role('button',name='Arquivar publicação',exact=True).click();host.wait_for_url('**status=archived');host.locator('.cx-post-header summary').click();host.get_by_role('button',name='Desarquivar',exact=True).click();expect(host.locator('[data-post]')).to_have_count(0);assert gc.request.get(url+'/api/community/posts/'+pid).ok
          guest.goto(url+'/comunidade/criar/series');guest.locator('[name=title]').fill('Episódios da nossa turma');guest.get_by_label('Gênero',exact=True).fill('Comédia');guest.get_by_label('Sinopse',exact=True).fill('Histórias do dia a dia.');guest.get_by_label('Foto por link').fill('https://example.com/cover.jpg');guest.locator('[data-ep=url]').fill('https://example.com/1.mp4');guest.get_by_role('button',name='Episódio',exact=True).click();guest.locator('[data-ep=title]').last.fill('A segunda história');guest.locator('[data-ep=url]').last.fill('https://example.com/2.mp4');assert guest.evaluate('document.documentElement.scrollWidth<=innerWidth');guest.screenshot(path=str(OUT/'experience-series-mobile.png'),full_page=True);guest.get_by_role('button',name='Publicar série',exact=True).click();guest.wait_for_url('**/comunidade/post/*');series=guest.url.rsplit('/',1)[-1];assert len(gc.request.get(url+'/api/community/posts/'+series).json()['post']['episodes'])==2
          guest.get_by_role('button',name='Assistir',exact=True).click();expect(guest.locator('.cx-episodes-player button')).to_have_count(2);guest.locator('.cx-episodes-player button').last.click();expect(guest.locator('.cx-episodes-player button').last).to_have_class(__import__('re').compile('selected'));guest.locator('#modal [data-action=close]').click()
          host.goto(url+'/comunidade/criar/reel');host.locator('[data-cx-upload=clips]').first.set_input_files([str(ROOT/'static/assets/hero.png'),str(ROOT/'static/assets/hero.png')]);expect(host.locator('#cx-clips>button')).to_have_count(2);host.locator('#cx-layout').select_option('grid');host.get_by_role('button',name='Aa Texto',exact=True).click();host.locator('[data-cx-layer=text]').fill('Nossa próxima história');host.locator('[data-cx-layer=text]').press('Tab');host.get_by_role('button',name='Link',exact=True).click();host.locator('[data-cx-layer=text]').fill('Descubra o filme');host.locator('[data-cx-layer=url]').fill('https://example.com/filme');host.locator('[data-cx-layer=url]').press('Tab');host.locator('[data-cx=emoji-add]').click();expect(host.locator('#cx-editor-preview .cx-layer')).to_have_count(3);host.get_by_role('button',name='Música',exact=True).click();host.get_by_label('Pesquisar no SoundCloud').fill('jazz');host.get_by_role('button',name='Buscar música',exact=True).click();expect(host.locator('#cx-music-results')).to_contain_text('conexão do SoundCloud');host.screenshot(path=str(OUT/'experience-reel-desktop.png'));host.get_by_role('button',name='Prévia',exact=True).click();host.wait_for_timeout(600);expect(host.locator('#cx-duration')).not_to_have_text('0:00');host.locator('.cx-steps [data-step="3"]').click();host.get_by_label('Legenda').fill('Uma colagem, muitas histórias');host.get_by_role('button',name='Publicar reel',exact=True).first.click();host.wait_for_url('**tab=reels');expect(host.locator('.cx-inline-reel .cx-layer')).to_have_count(3);host.get_by_role('button',name='Reproduzir reel',exact=True).click();expect(host.get_by_role('button',name='Pausar',exact=True)).to_be_visible()
          guest.goto(url+'/comunidade/criar/story');guest.get_by_role('button',name='Criar com texto',exact=True).click();guest.locator('[data-cx-layer=text]').fill('Cinema com a turma');guest.locator('[data-cx-layer=text]').press('Tab');guest.locator('[data-cx=emoji-add]').click();assert guest.evaluate('document.documentElement.scrollWidth<=innerWidth');guest.screenshot(path=str(OUT/'experience-story-mobile.png'),full_page=True);guest.locator('.cx-steps [data-step="3"]').click();guest.get_by_role('button',name='Publicar story',exact=True).first.click();guest.wait_for_url('**/comunidade');guest.locator('[data-sx=story-view]').first.click();expect(guest.locator('#cx-play-composition .cx-layer')).to_have_count(2);guest.locator('#modal [data-action=close]').click()
          guest.goto(url+'/comunidade/perfil/luna');guest.get_by_role('button',name='Editar perfil',exact=True).click();guest.locator('#cm-avatar-file').set_input_files(str(ROOT/'static/assets/hero.png'));guest.get_by_label('Zoom da foto').fill('2');guest.get_by_role('button',name='Usar este recorte').click();expect(guest.locator('#cm-profile [name=avatar]')).to_have_value(__import__('re').compile('data:image/png'))
          guest.locator('#cm-profile [data-sx-upload=cover]').set_input_files(str(ROOT/'static/assets/hero.png'));guest.get_by_role('button',name='Usar este recorte').click();expect(guest.locator('#cm-profile [name=cover]')).to_have_value(__import__('re').compile('/api/community/assets/'));guest.get_by_role('button',name='Salvar perfil',exact=True).click();expect(guest.locator('#cm-profile')).not_to_be_visible();expect(guest.locator('.cm-profile-details>.cm-avatar img')).to_be_visible()
          assert hc.request.get(url+'/api/play/horizonte').ok;assert hc.request.get(url+'/api/play/neon?episode='+episode).ok;host.goto(url+'/historico');expect(host.locator('.catalog-grid .movie-card')).to_have_count(2);host.screenshot(path=str(OUT/'experience-history-desktop.png'))
          hc.request.post(url+'/api/hub/dm/'+gid,headers=H,data={'body':'Mensagem para o contador'});guest.goto(url+'/comunidade');expect(guest.locator('.sx-mobile-nav [data-fh-unread]')).to_have_text('1',timeout=15000);expect(guest.locator('#fh-dock')).not_to_be_visible();expect(guest.get_by_role('button',name='Notificações',exact=True)).to_be_visible()
          assert hc.request.get(url+'/manifest.webmanifest').json()['start_url'].startswith('/comunidade')
          guest.add_init_script("Object.defineProperty(navigator,'standalone',{get:()=>true});");guest.reload();expect(guest.locator('#fh-pwa-welcome')).to_be_visible(timeout=15000);guest.screenshot(path=str(OUT/'experience-pwa-onboarding-mobile.png'));guest.locator('[data-hub=onboard-later]').click();expect(guest.locator('#fh-pwa-welcome')).not_to_be_visible()
          host.goto(url+'/admin?tab=settings');expect(host.locator('[name=soundcloud_client_id]')).to_be_visible();expect(host.locator('[name=soundcloud_client_id]')).to_have_value('')
          assert not errors,errors
          print(json.dumps({'catalog_movie_series':True,'episodes':True,'reels_collage_layers':True,'stories':True,'profile_crops':True,'comment_mentions_controls':True,'post_privacy_archive':True,'recent_watched':True,'mobile_badge_no_float':True,'pwa_onboarding':True,'soundcloud_admin_configuration':True,'page_errors':errors}))
        except Exception:
          for name,p in [('host',host),('guest',guest)]:
            try:p.screenshot(path=str(OUT/f'experience-failure-{name}.png'),full_page=True)
            except Exception:pass
          raise
        finally:browser.close()
    finally:server.shutdown()
