import React, {useEffect,useState} from 'react';
import {useApp,Action,PageHeading} from './shared.jsx';

export function DeviceLogin({onExpanded=()=>{}}){
 const {actions}=useApp();const [grant,setGrant]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[remaining,setRemaining]=useState(0);
 async function start(){setBusy(true);setError('');try{const value=await actions.request('/auth/device/start',{method:'POST',body:{kind:window.WorkTVPlatform?.tv?'tv':'browser'}});setGrant({...value,deadline:Date.now()+value.expires_in*1000});onExpanded(true);setRemaining(value.expires_in);}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{start();},[]);
 useEffect(()=>{if(!grant)return;let stopped=false,timer,clock;
  async function poll(){if(stopped)return;if(Date.now()>=grant.deadline){setError('Este QR Code expirou. Gere outro para entrar.');return;}
   try{const result=await actions.request('/auth/device/poll',{method:'POST',body:{id:grant.id}});if(stopped)return;if(result.status==='approved'){stopped=true;await actions.authenticated();return;}if(result.status!=='pending'){setError(result.status==='denied'?'A entrada foi recusada no celular.':'Este QR Code já foi utilizado.');return;}}
   catch(e){if(!stopped)setError(e.message);return;}if(!stopped)timer=setTimeout(poll,4000);
  }
  timer=setTimeout(poll,4000);clock=setInterval(()=>setRemaining(Math.max(0,Math.ceil((grant.deadline-Date.now())/1000))),1000);
  return()=>{stopped=true;clearTimeout(timer);clearInterval(clock);};
 },[grant]);
 return <section className="device-login" aria-label="Entrar com celular">
  {!grant?<button type="button" className="btn btn-secondary full-width" onClick={start} disabled={busy}>{busy?'Preparando…':'Entrar com QR Code'}</button>:<><h3>Entre pelo seu celular</h3><p>Escaneie o QR Code e confirme a entrada no WorkTV.</p><img className="login-qr" src={grant.qr} width="240" height="240" alt="QR Code para autorizar este aparelho"/><p>Confira este código no celular: <strong className="device-match">{grant.code}</strong></p><small>Expira em {remaining}s. A entrada só acontece após sua confirmação.</small><button type="button" className="text-button" disabled={busy} onClick={start}>Gerar outro QR Code</button><button type="button" className="text-button qr-password" onClick={()=>{setGrant(null);setError('');onExpanded(false);document.querySelector('#auth-email')?.focus();}}>Entrar com e-mail e senha</button></>}
  {error&&<p role="alert" className="form-error">{error}</p>}
 </section>;
}

export function ActivateDevice(){
 const {s,actions}=useApp();const [token]=useState(()=>{const value=location.hash.slice(1);if(/^[A-Za-z0-9_-]{43}$/.test(value)){sessionStorage.setItem('worktv-device-approval',value);history.replaceState(history.state,'','/ativar');return value;}return sessionStorage.getItem('worktv-device-approval')||'';});
 const [details,setDetails]=useState(null),[error,setError]=useState(''),[done,setDone]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;if(s.user&&token)actions.request('/auth/device/details',{method:'POST',body:{token}}).then(d=>{if(active)setDetails(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[s.user?.id,token]);
 async function decide(approved){setBusy(true);setError('');try{await actions.request('/auth/device/'+(approved?'approve':'deny'),{method:'POST',body:{token,code:details.code,confirmed:approved}});sessionStorage.removeItem('worktv-device-approval');setDone(approved?'Aparelho autorizado. O login será concluído na outra tela.':'Entrada recusada.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main id="main" className="page container access-page" data-react-page="activate"><h1>Entrar em outro aparelho</h1>{!token?<p>Escaneie o QR Code exibido na tela de entrada da TV ou do computador.</p>:!s.user?<><p>Entre na sua conta neste celular para conferir e autorizar o aparelho.</p><button className="btn btn-primary" onClick={()=>{sessionStorage.setItem('worktv-auth-return','/ativar');actions.login();}}>Entrar na minha conta</button></>:done?<p role="status">{done}</p>:details?<section className="surface"><h2>{details.label}</h2><p>Confirme que este código aparece no aparelho à sua frente:</p><strong className="device-match">{details.code}</strong><p>Você autorizará o acesso à conta de <strong>{s.user.name}</strong>. Só confirme se foi você quem pediu este acesso.</p><div className="access-actions"><button className="btn btn-primary" disabled={busy} onClick={()=>decide(true)}>Confirmar entrada</button><button className="btn btn-secondary" disabled={busy} onClick={()=>decide(false)}>Não fui eu</button></div></section>:!error?<p role="status">Conferindo o aparelho…</p>:null}{error&&<p role="alert" className="form-error">{error}</p>}</main>;
}

const colors=['blue','purple','green','orange','pink','cyan'];
export function Profiles(){
 const {s,actions}=useApp();const [profiles,setProfiles]=useState([]),[error,setError]=useState(''),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[remove,setRemove]=useState(null);
 const load=()=>actions.request('/profiles').then(d=>setProfiles(d.profiles));
 useEffect(()=>{if(s.user)load().catch(e=>setError(e.message));},[s.user?.id]);
 async function select(id){setBusy(true);try{await actions.selectProfile(id);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(e){e.preventDefault();e.stopPropagation();setBusy(true);setError('');try{const values=Object.fromEntries(new FormData(e.currentTarget));await actions.request('/profiles'+(editing.id?'/'+editing.id:''),{method:editing.id?'PATCH':'POST',body:values});setEditing(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function erase(){setBusy(true);setError('');try{await actions.request('/profiles/'+remove.id,{method:'DELETE',body:{}});setRemove(null);await actions.refreshState();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main id="main" className="page container access-page" data-react-page="profiles"><PageHeading title="Quem vai assistir?" subtitle="Até três perfis, cada um com sua lista e seu progresso."/>{!s.user?<Action action="login">Entrar na minha conta</Action>:<><div className="profiles-grid">{profiles.map(p=><article key={p.id} className="surface profile-card"><button type="button" className="profile-select" disabled={busy} onClick={()=>select(p.id)}><span className={'profile-symbol '+p.avatar}>{p.name[0].toUpperCase()}</span><strong>{p.name}</strong>{s.profile?.id===p.id&&<small>Perfil atual</small>}</button><div className="access-actions"><button className="text-button" onClick={()=>{setEditing(p);setRemove(null);}}>Editar</button>{profiles.length>1&&<button className="text-button" onClick={()=>{setRemove(p);setEditing(null);}}>Remover</button>}</div></article>)}{profiles.length<3&&!editing&&<button className="btn btn-secondary" onClick={()=>setEditing({name:'',avatar:'blue'})}>Adicionar perfil</button>}</div>
 {editing&&<form key={editing.id||'new'} className="surface" onSubmit={save}><h2>{editing.id?'Editar perfil':'Novo perfil'}</h2><div className="field"><label htmlFor="profile-name">Nome do perfil</label><input id="profile-name" name="name" defaultValue={editing.name} required maxLength="40"/></div><div className="field"><label htmlFor="profile-avatar">Cor do avatar</label><select id="profile-avatar" name="avatar" defaultValue={editing.avatar}>{colors.map((c,i)=><option value={c} key={c}>{['Azul','Roxo','Verde','Laranja','Rosa','Ciano'][i]}</option>)}</select></div><div className="access-actions"><button className="btn btn-primary" disabled={busy}>Salvar perfil</button><button type="button" className="text-button" onClick={()=>setEditing(null)}>Cancelar</button></div></form>}
 {remove&&<section className="surface" role="alert"><h2>Remover {remove.name}?</h2><p>A lista e o histórico deste perfil serão apagados. A assinatura e os outros perfis continuam disponíveis.</p><div className="access-actions"><button className="btn btn-primary" onClick={erase} disabled={busy}>Confirmar remoção</button><button className="text-button" onClick={()=>setRemove(null)}>Cancelar</button></div></section>}</>}{error&&<p role="alert" className="form-error">{error}</p>}</main>;
}

export function SecuritySettings(){
 const {actions}=useApp();const [info,setInfo]=useState(null),[setup,setSetup]=useState(null),[codes,setCodes]=useState(null),[mode,setMode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=()=>actions.request('/auth/security').then(setInfo);
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function submit(e){e.preventDefault();e.stopPropagation();const body=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{
  if(setup){const value=await actions.request('/auth/mfa/enable',{method:'POST',body});setCodes(value.recovery_codes);setSetup(null);setMode('');await load();}
  else if(mode==='disable'){await actions.request('/auth/mfa/disable',{method:'POST',body});setMode('');await load();}
  else setSetup(await actions.request('/auth/mfa/setup',{method:'POST',body}));
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="surface security-settings"><h2>Verificação em duas etapas</h2>{info&&<><p>{info.mfa_enabled?'Sua conta está protegida por um aplicativo autenticador.':'Adicione um código do autenticador ao entrar na sua conta.'}</p>{info.mfa_required&&!info.mfa_enabled&&<p className="notice">Ative esta proteção para acessar a administração.</p>}{!mode&&!setup&&!codes&&<div className="access-actions"><button className="btn btn-secondary" onClick={()=>setMode('setup')}>{info.mfa_enabled?'Trocar autenticador':'Ativar proteção'}</button>{info.mfa_enabled&&!info.mfa_required&&<button className="text-button" onClick={()=>setMode('disable')}>Desativar</button>}</div>}</>}
 {(mode||setup)&&<form onSubmit={submit}>{setup?<><p>Adicione esta chave ao seu aplicativo autenticador como uma conta WorkTV, usando códigos de seis dígitos a cada 30 segundos.</p><code className="mfa-secret">{setup.secret}</code><div className="field"><label htmlFor="mfa-code">Código do autenticador</label><input id="mfa-code" name="code" inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}" maxLength="6"/></div></>:<><div className="field"><label htmlFor="mfa-password">Confirme sua senha atual</label><input id="mfa-password" name="password" type="password" autoComplete="current-password" maxLength="128" required/></div>{info?.mfa_enabled&&<div className="field"><label htmlFor="mfa-existing">Código atual ou de recuperação</label><input id="mfa-existing" name="code" autoComplete="one-time-code" required maxLength="32"/></div>}</>}<div className="access-actions"><button className="btn btn-primary" disabled={busy}>{setup?'Confirmar ativação':mode==='disable'?'Confirmar desativação':'Continuar'}</button><button className="text-button" type="button" onClick={()=>{setSetup(null);setMode('');}}>Cancelar</button></div></form>}
 {codes&&<div role="status"><h3>Guarde seus códigos de recuperação</h3><p>Cada código funciona uma única vez. Eles não serão exibidos novamente. As outras sessões da conta foram encerradas.</p><pre className="recovery-codes">{codes.join('\n')}</pre><button className="btn btn-secondary" onClick={()=>setCodes(null)}>Guardei os códigos</button></div>}{error&&<p role="alert" className="form-error">{error}</p>}</section>;
}
